language: python
python:
  - "2.7"

# command to install dependencies
before_install:

  # Install ssh-agent if not already installed
  - 'which ssh-agent || ( sudo apt-get -qq update -y && sudo apt-get install openssh-client -y && which ssh-agent)'

  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  # make ssh directory
  - mkdir -p $HOME/.ssh

  # add ssh key stored in GITHUB_DEPLOY_SSH_KEY variable to the agent store
  # travis ci variables do not directly support new lines, so instead convert
  # whitespaces to new lines using perl on the key body with appropriate prefix
  # and suffix
  - (echo "-----BEGIN RSA PRIVATE KEY-----"; echo $GITHUB_DEPLOY_SSH_KEY | perl -pe 's/\s+/\n/g'; echo "-----END RSA PRIVATE KEY-----")
  - ssh-add <(echo "-----BEGIN RSA PRIVATE KEY-----"; echo $GITHUB_DEPLOY_SSH_KEY | perl -pe 's/\s+/\n/g'; echo "-----END RSA PRIVATE KEY-----")

  # For Docker builds disable host key checking. Be aware that by adding that
  # you are suspectible to man-in-the-middle attacks.
  # WARNING: Use this only with the Docker executor, if you use it with shell
  # you will overwrite your user's SSH config.
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > $HOME/.ssh/config'

  # install python requests module
  - "pip install requests"

  # tell git who you are
  - git config --global user.name "$GITHUB_NAME"
  - git config --global user.email "$GITHUB_EMAIL"

# command to run
script:

  # run python script
  - python github_stats.py

  # clone the github_stats_json repo from github.com
  - git clone git@github.com:welcheb/github_stats_json.git

  # change directory to github_stats_json
  - cd github_stats_json

  # copy json files generated by github_stats.py
  - cp ../*.json .

  # add any untracked json files
  - git add *.json

  # commit changes
  - git commit . -m "$(date -u)"

  # push
  - git push
